---
- name: Configure Join Commands on Master Node
  hosts: master
  become: true
  tasks:
    - name: Retrieve Join Command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command_raw
      changed_when: false

    - name: Set Join Command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join Worker Nodes
  hosts: workers
  become: true
  tasks:
    - name: Enable TCP port 6443 (On Master) is able to connect from Worker
      ansible.builtin.wait_for:
        host: "{{ hostvars['master']['ansible_default_ipv4']['address'] }}"
        port: 6443
        timeout: 1

    - name: Join worker to cluster
      ansible.builtin.shell: "{{ hostvars['master'].join_command }} >> node_joined.log"
      args:
        chdir: /home/ubuntu
        creates: node_joined.log
